package model;

public enum QuestionCategory {
    QUESTION_CATEGORY_1(1), QUESTION_CATEGORY_2(2), QUESTION_CATEGORY_3(3), QUESTION_CATEGORY_4(4), QUESTION_CATEGORY_5(5),
    QUESTION_CATEGORY_6(6), QUESTION_CATEGORY_7(7), QUESTION_CATEGORY_8(8), QUESTION_CATEGORY_9(9), QUESTION_CATEGORY_10(10),
    QUESTION_CATEGORY_11(11), QUESTION_CATEGORY_12(12), QUESTION_CATEGORY_13(13), QUESTION_CATEGORY_14(14), QUESTION_CATEGORY_15(15),
    QUESTION_CATEGORY_16(16), QUESTION_CATEGORY_17(17), QUESTION_CATEGORY_18(18), QUESTION_CATEGORY_19(19), QUESTION_CATEGORY_20(20);

    private final int ID;

    QuestionCategory(int ID) {
        this.ID = ID;
    }

    public int getID() {
        return ID;
    }
}
